//
// Generated file, do not edit! Created by nedtool 5.6 from caso3.msg.
//

#ifndef __CASO3_M_H
#define __CASO3_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>caso3.msg:12</tt> by nedtool.
 * <pre>
 * packet Caso3Pkt
 * {
 *     simtime_t initTime;
 *     int flowId;
 *     int flowSeqNum;
 *     int linkSeqNum;
 * 
 * 
 * }
 * </pre>
 */
class Caso3Pkt : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t initTime;
    int flowId;
    int flowSeqNum;
    int linkSeqNum;

  private:
    void copy(const Caso3Pkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Caso3Pkt&);

  public:
    Caso3Pkt(const char *name=nullptr, short kind=0);
    Caso3Pkt(const Caso3Pkt& other);
    virtual ~Caso3Pkt();
    Caso3Pkt& operator=(const Caso3Pkt& other);
    virtual Caso3Pkt *dup() const override {return new Caso3Pkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getInitTime() const;
    virtual void setInitTime(::omnetpp::simtime_t initTime);
    virtual int getFlowId() const;
    virtual void setFlowId(int flowId);
    virtual int getFlowSeqNum() const;
    virtual void setFlowSeqNum(int flowSeqNum);
    virtual int getLinkSeqNum() const;
    virtual void setLinkSeqNum(int linkSeqNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Caso3Pkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Caso3Pkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CASO3_M_H

